### ISSUE TITLE
Comments on chapter 5

### ISSUE THREAD

**Issue by dicook** [sa-lee/thesis#6]
- i really like the sectioning and the flow of the chapter
- there is a three which should be a tree (somewhere)
- add links to the vimeo site for each video, in the caption, and use a still shot in the pdf (its so nice seeing the videos in the html, but this doesn't port to pdf easily)
- use of "visual analytics" should be removed: "We present a visual analytics framework for the pragmatic usage of NLDR methods by combining them with a technique called the tour." would change this sentence (maybe we do this together when we meet, to revise the abstract)
- also needs to be in third person - although i see that you have used first person in the other chapters, so it could be thesis consistent to keep it this way.
- representative the (missing an "of")
- visualization.Given (missing space)
- tour references should be extended, and also there is a ggvis program linking MDS with a tour by Swayne and Buja around 2005. 
- avoid "aforementioned"
- the last paragraph in the intro should be a "This paper is organised as follows. The next section ..."
- use a proper citation to the liminal package, rather than a URL in the text. 
- Not sure that this is the right reference: "We have made extensive use of ensemble graphics, that is aligning related plots alongside each other to provide context (Unwin and Valero-Mora, 2018)". Better to reference linked brushing, and you can point to the first paper on this by McDonald, I think, and maybe dataviewer and xgobi which link tours to other displays
- i love the distortions and diffusions description
- maybe just refer to one-to-one linking in 5.3.3 and shift the other types of linking to discussion?
- you use "we propose" a lot. I think its better to say you have done something, and talk about your work as making an advance. you could include a paragraph in the conclusion which has more about "we propose this approach be adopted" and discuss some options for implementation beyond liminal, in any system with a tour implementation and the ability to link views.
- don't think this is the right reference: liminal (R Core Team, 2019b).
- explanation of tours should go earlier, maybe 5.2. In the software infrastructure you can talk about how the tourr package implementation determines liminal capabilities
- "The next section steps through case studies" to "This section illustrates the ideas and the liminal implementation on several case studies."
- "We see in this case that is difficult" (missing a "that")
- make smaller subsections, or at least italicised paragraph headings for the simulated data

Looking good!

(notice some code fragments in chapter 3 going outside the box)

**Comment by sa-lee** [comment]
Notes from yesterday: 

- clean up screenshots
- guide the reader to actually look at the videos
